Remove caching to avoid typescript errors
```
 FAIL  test/app.test.ts
  ● Test suite failed to run

    src/utils.ts:16:10 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
      No index signature with a parameter of type 'string' was found on type '{}'.

    16     if (!cache[jsonString as string]) {
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/utils.ts:18:9 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
      No index signature with a parameter of type 'string' was found on type '{}'.

    18         cache[jsonString as string] = JSON.parse(jsonString);
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    src/utils.ts:25:12 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
      No index signature with a parameter of type 'string' was found on type '{}'.

    25     return cache[jsonString as string];
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```